import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import { Suspense } from "react";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <main className="flex-grow  bg-gradient-to-b from-blue-50 to-white">
            <Suspense fallback={<div>Loading...</div>}>
            <Header />
              {children}
            </Suspense>
          </main>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
