export const PREDEFINED_QUESTIONS = [
    "What's the best ice cream flavor?",
    "If you could only eat one type of cuisine forever, what would it be?",
    "What's the ideal vacation destination?",
    "Which animal would make the best pet?",
    "What's the most overrated movie?",
    "What's your favorite season?",
    "If you had to wear one color for the rest of your life, what would it be?",
    "What's the best breakfast food?",
    "What's the worst household chore?",
    "Which vegetable would you eliminate from the planet?",
    "What's the best time to wake up on weekends?",
    "What's the worst thing to forget at home?",
    "What's the best place for a first date?",
    "What's the most iconic TV show of all time?",
    "If you could only watch one sport, what would it be?",
    "What's the best dessert?",
    "If you could be an expert in one skill, what would it be?",
    "What's the best way to spend a rainy day?",
    "What's the best type of pet: dog, cat, fish, or hamster?",
    "What's the most stressful holiday?",
    "What's the best age to be?",
    "If you had to listen to one song forever, what would it be?",
    "What's the best type of cheese?",
    "If you had to give up one modern convenience, what would it be?",
    "What's the most exciting holiday tradition?"
  ];
  